export const TEXTS = {
    uz: {
        choose_lang: "Iltimos, tilni tanlang:\n\nПожалуйста, выберите язык:\n\nPlease select a language:",
        main_menu: "Asosiy menyu:",
        btn_tender_uz: "O‘zbekiston tender yangiliklari",
        btn_exh_uz: "O‘zbekistondagi ko‘rgazmalar",
        btn_exh_glb: "Dunyo bo‘ylab ko‘rgazmalar",
        btn_products: "Internetda (O‘zbekistonda) eng ko‘p qidirilgan mahsulotlar",
        msg_tender_uz: "📍 <b>O‘zbekiston tender yangiliklari:</b>\n[ AI orqali real tenderlarni qidirish qismi ]",
        msg_exh_uz: "📍 <b>O‘zbekistondagi ko‘rgazmalar:</b>\n[ AI tahlili orqali yaqinlashib kelayotgan ko'rgazmalar ]",
        msg_exh_glb: "📍 <b>Dunyo bo‘ylab ko‘rgazmalar:</b>\n[ AI orqali yirik dunyo ko'rgazmalari ro'yxati ]",
        msg_products: "📍 <b>Eng ko‘p qidirilgan mahsulotlar:</b>\n[ AI trendlar statistikasi asosida ma'lumot qismi ]",
        unknown_command: "Iltimos, pastdagi menyudan kerakli bo'limni tanlang.",
        
        btn_settings: "⚙️ Sozlamalar",
        btn_exit_admin: "🚪 Chiqish",
        btn_change_password: "🔑 Parolni o'zgartirish",
        msg_settings_password: "Iltimos, admin paneliga kirish uchun parolni kiriting:",
        msg_wrong_password: "❌ Noto'g'ri parol!",
        msg_admin_menu: "Xush kelibsiz! Admin menyusidasiz.",
        
        msg_ask_old_password: "🔐 O'zgartirish uchun avval <b>Hozirgi parolingizni</b> kiriting:",
        msg_ask_new_password: "🆕 Yaxshi! Endi <b>Yangi parolni</b> kiriting:",
        msg_ask_confirm_password: "🔁 Yangi parolni xatosiz ekanligiga ishonch hosil qilish uchun <b>Yana bir marta</b> kiriting:",
        msg_password_changed: "✅ Parol muvaffaqiyatli almashtirildi!",
        msg_password_mismatch: "❌ Parollar bir xil emas yoki hozirgisi noto'g'ri. Jarayon bekor qilindi.",

        btn_channels: "📢 Kanallar",
        msg_channels_list: "Ulangan kanallar ro'yxati:",
        btn_add_channel: "➕ Yangi qo'shish",
        btn_delete_channel: "➖ O'chirish",
        btn_back: "🔙 Ortga",
        msg_add_channel: "Yangi kanal logini yoki IDsini kiriting (Masalan: @kanal_nimadir yoki -100123...):",
        msg_delete_channel: "Ro'yxatdan o'chirib tashlamoqchi bo'lgan kanalni yozing:",
        msg_channel_added: "✅ Kanal muvaffaqiyatli qo'shildi!",
        msg_channel_deleted: "🗑 Kanal muvaffaqiyatli o'chirib tashlandi!",
        msg_channel_not_found: "❌ Ushbu kanal bazada topilmadi.",
        msg_channel_verify_error: "❌ Bot ushbu kanalga xabar yubora olmadi! Kanal nomi to'g'riligiga va bot kanalga administrator qilinganiga ishonch hosil qiling.",

        btn_websites: "🌐 Web saytlar",
        msg_websites_list: "Ulangan web saytlar ro'yxati:",
        btn_add_website: "➕ Sayt qo'shish",
        btn_delete_website: "➖ Saytni o'chirish",
        msg_add_website: "Yangi web sayt manzilini kiriting (Masalan: https://example.com):",
        msg_delete_website: "Ro'yxatdan o'chirib tashlamoqchi bo'lgan saytni yozing:",
        msg_website_added: "✅ Web sayt muvaffaqiyatli qo'shildi!",
        msg_website_deleted: "🗑 Web sayt muvaffaqiyatli o'chirib tashlandi!",
        msg_website_not_found: "❌ Ushbu sayt bazada topilmadi.",
        msg_ask_website_cookie: "Endi ushbu sayt uchun <b>Cookie</b> ni kiriting (Agar login shart bo'lmasa 'no' deb yozing):",
        msg_cookie_update_required: "⚠️ Diqqat! <b>{url}</b> sayti uchun cookie eskirgan yoki xato. Iltimos, admin panelda uni yangilang.",

        btn_keywords: "🔑 Qidiruv so'zlari",
        msg_keywords_list: "Qidiruv so'zlari ro'yxati:",
        btn_add_keyword: "➕ So'z qo'shish",
        btn_delete_keyword: "➖ So'zni o'chirish",
        msg_add_keyword: "Yangi qidiruv so'zini kiriting (Masalan: IT tender):",
        msg_delete_keyword: "Ro'yxatdan o'chirib tashlamoqchi bo'lgan so'zni yozing:",
        msg_keyword_added: "✅ Qidiruv so'zi muvaffaqiyatli qo'shildi!",
        msg_keyword_deleted: "🗑 Qidiruv so'zi muvaffaqiyatli o'chirib tashlandi!",
        msg_keyword_not_found: "❌ Ushbu so'z bazada topilmadi.",

        btn_schedules: "⏳ Jo'natish vaqtlari",
        msg_schedules_list: "Xabar jo'natish vaqtlari ro'yxati (Toshkent vaqti bilan):",
        btn_add_time: "➕ Vaqt qo'shish",
        btn_delete_time: "➖ Vaqtni o'chirish",
        msg_add_time: "Yangi vaqtni HH:MM formatida kiriting (Masalan: 14:30 yoki 08:00):",
        msg_delete_time: "O'chirib tashlamoqchi bo'lgan vaqtni kiriting (Masalan: 08:00):",
        msg_time_added: "✅ Vaqt muvaffaqiyatli qo'shildi!",
        msg_time_deleted: "🗑 Vaqt muvaffaqiyatli o'chirib tashlandi!",
        msg_time_not_found: "❌ Ushbu vaqt ro'yxatda topilmadi.",
        msg_invalid_time_format: "❌ Noto'g'ri format! Vaqtni HH:MM formatida kiriting.",

        btn_openai_token: "🤖 OpenAI Token",
        btn_add_token: "➕ Token kiritish",
        btn_delete_token: "➖ Tokenni o'chirish",
        msg_token_status: "Hozirgi OpenAI token holati:\n\n",
        msg_ask_token: "Yangi OpenAI tokenni yuboring (Masalan: sk-proj-...):",
        msg_token_saved: "✅ OpenAI token muvaffaqiyatli saqlandi!",
        msg_token_deleted: "🗑 OpenAI token muvaffaqiyatli o'chirildi!",

        btn_message_prompt: "💬 Xabarning promti",
        btn_add_msg_prompt: "➕ Promtni kirgizish",
        btn_del_msg_prompt: "➖ Promtni olib tashlash",
        btn_test_msg_prompt: "🧪 Sinov uchun yuborish",
        msg_ask_msg_prompt: "Yangi xabar promtini kiriting (u saytlar va kalit so'zlar bilan birga OpenAI ga yuboriladi):",
        msg_msg_prompt_saved: "✅ Promt muvaffaqiyatli saqlandi!",
        msg_msg_prompt_deleted: "🗑 Promt o'chirib tashlandi!",
        msg_msg_prompt_status: "Hozirgi Xabar Promti holati:\n\n",
        msg_test_sending: "⏳ Xabar shakllantirilmoqda va OpenAI ga yuborilmoqda. Iltimos kuting...",
        msg_test_success: "✅ Sinov xabari qabul qilindi!",
        msg_test_error: "❌ Xatolik yuz berdi. Iltimos OpenAI token va boshqa sozlamalarni tekshiring.",

        btn_prompts: "📝 Promptlar",
        btn_add_prompt: "➕ Prompt qo'shish",
        btn_delete_prompt: "➖ Promptni o'chirish",
        msg_prompts_list: "Bazada mavjud promptlar ro'yxati:",
        msg_ask_prompt_id: "Yangi prompt uchun qisqacha ID nomini kiriting (Masalan: tender_prompt):",
        msg_ask_prompt_text: "Yaxshi! Endi ushbu prompt matnini yuboring:",
        msg_prompt_saved: "✅ Prompt muvaffaqiyatli saqlandi!",
        msg_prompt_deleted: "🗑 Prompt o'chirildi!",
        msg_prompt_not_found: "❌ Bunday ID li prompt topilmadi."
    },
    ru: {
        choose_lang: "Пожалуйста, выберите язык:",
        main_menu: "Главное меню:",
        btn_tender_uz: "Тендерные новости Узбекистана",
        btn_exh_uz: "Выставки в Узбекистане",
        btn_exh_glb: "Международные выставки",
        btn_products: "Самые популярные товары в Узбекистане",
        msg_tender_uz: "📍 <b>Тендерные новости Узбекистана:</b>\n[ Место для работы ИИ по поиску тендеров ]",
        msg_exh_uz: "📍 <b>Выставки в Узбекистане:</b>\n[ Место для информации о выставках от ИИ ]",
        msg_exh_glb: "📍 <b>Международные выставки:</b>\n[ Место для данных ИИ о глобальных выставках ]",
        msg_products: "📍 <b>Популярные товары:</b>\n[ Аналитика трендов от ИИ ]",
        unknown_command: "Пожалуйста, выберите раздел из предложенного меню.",
        
        btn_settings: "⚙️ Настройки",
        btn_exit_admin: "🚪 Выход",
        btn_change_password: "🔑 Изменить пароль",
        msg_settings_password: "Пожалуйста, введите пароль для доступа к админ панели:",
        msg_wrong_password: "❌ Неверный пароль!",
        msg_admin_menu: "Добро пожаловать в админ панель.",
        
        msg_ask_old_password: "🔐 Сначала введите <b>Текущий пароль</b>:",
        msg_ask_new_password: "🆕 Отлично! Теперь введите <b>Новый пароль</b>:",
        msg_ask_confirm_password: "🔁 Пожалуйста, введите новый пароль <b>еще раз</b> для подтверждения:",
        msg_password_changed: "✅ Пароль успешно изменен!",
        msg_password_mismatch: "❌ Пароли не совпадают или неверный текущий пароль. Операция отменена.",

        btn_channels: "📢 Каналы",
        msg_channels_list: "Список каналов:",
        btn_add_channel: "➕ Добавить",
        btn_delete_channel: "➖ Удалить",
        btn_back: "🔙 Назад",
        msg_add_channel: "Введите ID или логин канала:",
        msg_delete_channel: "Введите канал который хотите удалить:",
        msg_channel_added: "✅ Канал успешно добавлен!",
        msg_channel_deleted: "🗑 Канал успешно удален!",
        msg_channel_not_found: "❌ Канал не найден.",
        msg_channel_verify_error: "❌ Ошибка! Проверьте права администратора у бота в канале.",

        btn_websites: "🌐 Веб-сайты",
        msg_websites_list: "Список веб-сайтов:",
        btn_add_website: "➕ Добавить сайт",
        btn_delete_website: "➖ Удалить сайт",
        msg_add_website: "Введите адрес нового сайта (Например: https://example.com):",
        msg_delete_website: "Введите сайт который хотите удалить:",
        msg_website_added: "✅ Веб-сайт успешно добавлен!",
        msg_website_deleted: "🗑 Веб-сайт успешно удален!",
        msg_website_not_found: "❌ Веб-сайт не найден.",
        msg_ask_website_cookie: "Теперь введите <b>Cookie</b> для этого сайта (Если логин не требуется, напишите 'no'):",
        msg_cookie_update_required: "⚠️ Внимание! Cookie для сайта <b>{url}</b> устарели или неверны. Пожалуйста, обновите их в админ панели.",

        btn_keywords: "🔑 Ключевые слова",
        msg_keywords_list: "Список ключевых слов для поиска:",
        btn_add_keyword: "➕ Добавить слово",
        btn_delete_keyword: "➖ Удалить слово",
        msg_add_keyword: "Введите новое ключевое слово (Например: IT тендер):",
        msg_delete_keyword: "Введите слово которое хотите удалить:",
        msg_keyword_added: "✅ Ключевое слово успешно добавлено!",
        msg_keyword_deleted: "🗑 Ключевое слово успешно удалено!",
        msg_keyword_not_found: "❌ Ключевое слово не найдено.",

        btn_schedules: "⏳ Время отправки",
        msg_schedules_list: "Список времени отправки сообщений (По Ташкенту):",
        btn_add_time: "➕ Добавить время",
        btn_delete_time: "➖ Удалить время",
        msg_add_time: "Введите новое время в формате HH:MM (Например: 14:30 или 08:00):",
        msg_delete_time: "Введите время, которое хотите удалить (Например: 08:00):",
        msg_time_added: "✅ Время успешно добавлено!",
        msg_time_deleted: "🗑 Время успешно удалено!",
        msg_time_not_found: "❌ Это время не найдено в списке.",
        msg_invalid_time_format: "❌ Неверный формат! Введите время в формате HH:MM.",

        btn_openai_token: "🤖 OpenAI Token",
        btn_add_token: "➕ Добавить токен",
        btn_delete_token: "➖ Удалить токен",
        msg_token_status: "Текущее состояние OpenAI токена:\n\n",
        msg_ask_token: "Отправьте новый токен OpenAI (Например: sk-proj-...):",
        msg_token_saved: "✅ OpenAI токен успешно сохранен!",
        msg_token_deleted: "🗑 OpenAI токен успешно удален!",

        btn_message_prompt: "💬 Промпт сообщения",
        btn_add_msg_prompt: "➕ Ввести промпт",
        btn_del_msg_prompt: "➖ Удалить промпт",
        btn_test_msg_prompt: "🧪 Отправить для теста",
        msg_ask_msg_prompt: "Введите новый промпт сообщения (он будет отправлен в OpenAI вместе с сайтами и ключами):",
        msg_msg_prompt_saved: "✅ Промпт успешно сохранен!",
        msg_msg_prompt_deleted: "🗑 Промпт удален!",
        msg_msg_prompt_status: "Текущее состояние промпта:\n\n",
        msg_test_sending: "⏳ Сообщение формируется и отправляется в OpenAI. Пожалуйста, подождите...",
        msg_test_success: "✅ Тестовое сообщение получено!",
        msg_test_error: "❌ Произошла ошибка. Проверьте токен OpenAI и другие настройки.",

        btn_prompts: "📝 Промпты",
        btn_add_prompt: "➕ Добавить промпт",
        btn_delete_prompt: "➖ Удалить промпт",
        msg_prompts_list: "Список доступных промптов:",
        msg_ask_prompt_id: "Введите ID для нового промпта (Например: tender_prompt):",
        msg_ask_prompt_text: "Отлично. Теперь отправьте текст этого промпта:",
        msg_prompt_saved: "✅ Промпт успешно сохранен!",
        msg_prompt_deleted: "🗑 Промпт удален!",
        msg_prompt_not_found: "❌ Промпт с таким ID не найден."
    },
    en: {
        choose_lang: "Please select a language:",
        main_menu: "Main menu:",
        btn_tender_uz: "Uzbekistan tender news",
        btn_exh_uz: "Exhibitions in Uzbekistan",
        btn_exh_glb: "Global exhibitions",
        btn_products: "Most searched products in Uzbekistan",
        msg_tender_uz: "📍 <b>Uzbekistan tender news:</b>\n[ AI placeholder for reading live tender news ]",
        msg_exh_uz: "📍 <b>Exhibitions in Uzbekistan:</b>\n[ AI placeholder for local exhibitions ]",
        msg_exh_glb: "📍 <b>Global exhibitions:</b>\n[ AI placeholder for global exhibitions ]",
        msg_products: "📍 <b>Most searched products:</b>\n[ AI placeholder for analytics and trend stats ]",
        unknown_command: "Please select an option from the menu below.",

        btn_settings: "⚙️ Settings",
        btn_exit_admin: "🚪 Exit",
        btn_change_password: "🔑 Change password",
        msg_settings_password: "Please enter password to access admin panel:",
        msg_wrong_password: "❌ Wrong password!",
        msg_admin_menu: "Welcome to Admin panel.",
        
        msg_ask_old_password: "🔐 First, please enter your <b>Current password</b>:",
        msg_ask_new_password: "🆕 Great! Now enter the <b>New password</b>:",
        msg_ask_confirm_password: "🔁 Please type the new password <b>once again</b> to confirm:",
        msg_password_changed: "✅ Password changed successfully!",
        msg_password_mismatch: "❌ Passwords mismatch or invalid current password. Operation cancelled.",

        btn_channels: "📢 Channels",
        msg_channels_list: "Connected channels:",
        btn_add_channel: "➕ Add new",
        btn_delete_channel: "➖ Delete",
        btn_back: "🔙 Back",
        msg_add_channel: "Enter channel ID or username:",
        msg_delete_channel: "Enter the channel you want to delete:",
        msg_channel_added: "✅ Channel successfully added!",
        msg_channel_deleted: "🗑 Channel deleted!",
        msg_channel_not_found: "❌ Channel not found.",
        msg_channel_verify_error: "❌ Could not verify channel. Is the bot an admin?",

        btn_websites: "🌐 Websites",
        msg_websites_list: "Connected websites:",
        btn_add_website: "➕ Add website",
        btn_delete_website: "➖ Delete website",
        msg_add_website: "Enter new website URL (e.g., https://example.com):",
        msg_delete_website: "Enter the website you want to delete:",
        msg_website_added: "✅ Website successfully added!",
        msg_website_deleted: "🗑 Website deleted!",
        msg_website_not_found: "❌ Website not found.",
        msg_ask_website_cookie: "Now enter the <b>Cookie</b> for this website (If login is not required, type 'no'):",
        msg_cookie_update_required: "⚠️ Warning! Cookies for <b>{url}</b> have expired or are invalid. Please update them in the admin panel.",

        btn_keywords: "🔑 Search keywords",
        msg_keywords_list: "List of search keywords:",
        btn_add_keyword: "➕ Add keyword",
        btn_delete_keyword: "➖ Delete keyword",
        msg_add_keyword: "Enter new search keyword (e.g., IT tender):",
        msg_delete_keyword: "Enter the keyword you want to delete:",
        msg_keyword_added: "✅ Keyword successfully added!",
        msg_keyword_deleted: "🗑 Keyword deleted!",
        msg_keyword_not_found: "❌ Keyword not found.",

        btn_schedules: "⏳ Sending schedules",
        msg_schedules_list: "List of message sending times (Tashkent time):",
        btn_add_time: "➕ Add time",
        btn_delete_time: "➖ Delete time",
        msg_add_time: "Enter new time in HH:MM format (e.g., 14:30 or 08:00):",
        msg_delete_time: "Enter the time you want to delete (e.g., 08:00):",
        msg_time_added: "✅ Time successfully added!",
        msg_time_deleted: "🗑 Time successfully deleted!",
        msg_time_not_found: "❌ This time was not found in the list.",
        msg_invalid_time_format: "❌ Invalid format! Please enter time in HH:MM format.",

        btn_openai_token: "🤖 OpenAI Token",
        btn_add_token: "➕ Add token",
        btn_delete_token: "➖ Delete token",
        msg_token_status: "Current OpenAI token status:\n\n",
        msg_ask_token: "Send the new OpenAI token (e.g., sk-proj-...):",
        msg_token_saved: "✅ OpenAI token successfully saved!",
        msg_token_deleted: "🗑 OpenAI token successfully deleted!",

        btn_message_prompt: "💬 Message prompt",
        btn_add_msg_prompt: "➕ Enter prompt",
        btn_del_msg_prompt: "➖ Remove prompt",
        btn_test_msg_prompt: "🧪 Send for test",
        msg_ask_msg_prompt: "Enter new message prompt (it will be sent to OpenAI along with websites and keywords):",
        msg_msg_prompt_saved: "✅ Prompt successfully saved!",
        msg_msg_prompt_deleted: "🗑 Prompt deleted!",
        msg_msg_prompt_status: "Current Message Prompt status:\n\n",
        msg_test_sending: "⏳ Message is being formed and sent to OpenAI. Please wait...",
        msg_test_success: "✅ Test message received!",
        msg_test_error: "❌ An error occurred. Please check OpenAI token and other settings.",

        btn_prompts: "📝 Prompts",
        btn_add_prompt: "➕ Add prompt",
        btn_delete_prompt: "➖ Delete prompt",
        msg_prompts_list: "List of available prompts:",
        msg_ask_prompt_id: "Enter an ID for the new prompt (e.g., tender_prompt):",
        msg_ask_prompt_text: "Great. Now send the text for this prompt:",
        msg_prompt_saved: "✅ Prompt successfully saved!",
        msg_prompt_deleted: "🗑 Prompt deleted!",
        msg_prompt_not_found: "❌ Prompt with this ID not found."
    }
};
